---
- hosts: app_vm
  become: true
  tasks:
    - name: Network for containers
      docker_network:
        name: super_network
        connected:
          - api
          - website

    - name: Copy simple_api
      copy:
        src: /var/lib/jenkins/workspace/GITHUB_CLONE/simple_api
        dest: /root
        mode: '0644'

    - name: Copy website
      copy:
        src: /var/lib/jenkins/workspace/GITHUB_CLONE/website
        dest: /root
        mode: '0644'

    - name: Deploy simple_api
      docker_container:
        name: api
        hostname: api

        image: 305764/img:latest
        #image: myregistry.local:5000/test:latest
        state: started
        volumes:
          - "/root/simple_api/student_age.json:/data/student_age.json"
        ports:
          - "5000:5000"

    - name: Deploy website
      docker_container:
        name: website
        hostname: website
        image: php:apache
        state: started
        volumes:
          - "/root/website/index.php:/var/www/html/index.php"
        env:
          USERNAME: "toto"
          PASSWORD: "python"
        ports:
          - "80:80"
