version: '3'
services:
    api:

        image: 305764/img:latest
        #image: myregistry.local:5000/test:latest
        volumes:
            - ./simple_api/student_age.json:/data/student_age.json
        ports:
            - 5000:5000

    website:
        image: php:apache
        environment:
            - USERNAME=toto
            - PASSWORD=python
        volumes:
            - ./website:/var/www/html
        depends_on:
            - api
        ports:
            - 80:80
